- platform: tplink
  host: 192.168.86.27
  friendly_name: 'display'
  username: robsonschmidt@gmail.com
  password: 14253678
- platform: tplink
  host: 192.168.86.41
  friendly_name: 'garden_light'
  username: robsonschmidt@gmail.com
  password: 14253678
- platform: broadlink
  host: 192.168.86.43
  mac: '34:EA:34:B3:00:CB'
  friendly_name: 'Suite'
  type: rm_mini
  timeout: 60
  switches:
    power_net_q:
      friendly_name: 'Power Net Quarto'
      command_on: 'JgBQAAABJZIXMhY0FzIWDhUQExEUERYzFg8WMxYzFjMVNRMREzYTEhMSFTQWDhYRFDMWDxYOFRAROBMSEzYTNhMSEzYTNhU0FgAE7QABKEYWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJZIXMhY0FzIWDhUQExEUERYzFg8WMxYzFjMVNRMREzYTEhMSFTQWDhYRFDMWDxYOFRAROBMSEzYTNhMSEzYTNhU0FgAE7QABKEYWAA0FAAAAAAAAAAA='
    power_tv_q:
      friendly_name: 'Power TV Quarto'
      command_on: 'JgBUAA0AAakAASaSFw0WDxYOFRAUERMRExIVDxYzFzMWMxM2EzYUNRYPFjMXMhY0FBATEhcOFQ8WEBIRExITERM2EzcXMhYzFzIUNRMABTkAASVKEwANBQAAAAA='
      command_off: 'JgBUAA0AAakAASaSFw0WDxYOFRAUERMRExIVDxYzFzMWMxM2EzYUNRYPFjMXMhY0FBATEhcOFQ8WEBIRExITERM2EzcXMhYzFzIUNRMABTkAASVKEwANBQAAAAA='
    source_tv_q:
      friendly_name: 'Source TV Quarto'
      command_on: 'JgBQAAABJZETEhURFg8VEBUQFREVEBUSFDQSNxM3EzYTMxk0Fg8TNhMTFDUTNhQ2EjcTExISFhASNxYRFRETEhMQFTUWMxM2FAAFPgABJEoSAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJZETEhURFg8VEBUQFREVEBUSFDQSNxM3EzYTMxk0Fg8TNhMTFDUTNhQ2EjcTExISFhASNxYRFRETEhMQFTUWMxM2FAAFPgABJEoSAA0FAAAAAAAAAAA='
    vol_up_tv_q:
      friendly_name: 'Vol Cima TV Quarto'
      command_on: 'JgBUAAABJo4YDxYPFRAUFBITEhMTExISFjQWNBYzFjMTNxU0FBISNhQSEzcSNxcOFjMWEBcOFg8TNxITExMSNhQSEjcTNxU0FgAFPAABJ0cWAAv/CwANBQAAAAA='
      command_off: 'JgBUAAABJo4YDxYPFRAUFBITEhMTExISFjQWNBYzFjMTNxU0FBISNhQSEzcSNxcOFjMWEBcOFg8TNxITExMSNhQSEjcTNxU0FgAFPAABJ0cWAAv/CwANBQAAAAA='
    vol_down_tv_q:
      friendly_name: 'Vol Baixo TV Quarto'
      command_on: 'JgBYAAABJ44WDxMTFRATEhMSExMSExMTEjYUNhM3FjMWMxY0Fg8WMxcOFDYTExI2FzMWDxUTExAVNBYREjYTEhMSFTUTNxI2FgAFPAABJEoVAAxKAAEkShIADQU='
      command_off: 'JgBYAAABJ44WDxMTFRATEhMSExMSExMTEjYUNhM3FjMWMxY0Fg8WMxcOFDYTExI2FzMWDxUTExAVNBYREjYTEhMSFTUTNxI2FgAFPAABJEoVAAxKAAEkShIADQU='
    ch_up_net_q:
      friendly_name: 'Canal Cima Net Quarto'
      command_on: 'JgBQAAABJY8WNBg0FzITERMSExIVDxcyFg8XMhQ1FjMXMxYOFzIUERMSFQ8VEBYQEzQXDhYQExEUNRY0FjMWMxYPFjMWMxM2FAAE7wABJUkXAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJY8WNBg0FzITERMSExIVDxcyFg8XMhQ1FjMXMxYOFzIUERMSFQ8VEBYQEzQXDhYQExEUNRY0FjMWMxYPFjMWMxM2FAAE7wABJUkXAA0FAAAAAAAAAAA='
    ch_down_net_q:
      friendly_name: 'Canal Baixo Net Quarto'
      command_on: 'JgBSAApOAAEnkhQ1EzYXMhYPFg4XDhQREzYTERcyFzMUNRcyFw4ROBQQFBEVNBYPFzITNhQRFw0WERQzFw4ROBQQExIWNBUzEzcWAATsAAEoRxcADQUAAAAAAAA='
      command_off: 'JgBSAApOAAEnkhQ1EzYXMhYPFg4XDhQREzYTERcyFzMUNRcyFw4ROBQQFBEVNBYPFzITNhQRFw0WERQzFw4ROBQQExIWNBUzEzcWAATsAAEoRxcADQUAAAAAAAA='
    up_tv_q:
      friendly_name: 'Cima TV Quarto'
      command_on: 'JgBQAAABJJEXDhUREhMVFRQaFRIQFBQREjYUNhM3EzYWMxY0EhMWNBI2Fw8WNBYzFjMWDxURExIVEBY0EhMWEBISFzMWMxY0FQAFPAABJkgTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJJEXDhUREhMVFRQaFRIQFBQREjYUNhM3EzYWMxY0EhMWNBI2Fw8WNBYzFjMWDxURExIVEBY0EhMWEBISFzMWMxY0FQAFPAABJkgTAA0FAAAAAAAAAAA='
    down_tv_q:
      friendly_name: 'Baixo TV Quarto'
      command_on: 'JgBQAAABJJEWEBITFRESEhcPEhUTERITFTQWPxczFzIVNBM3ExMUNRM1FBIVNRYPFg8UEhQ1FhAVDxE5ExITNxM2EjcTExM2EwAFPwABJEkTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJJEWEBITFRESEhcPEhUTERITFTQWPxczFzIVNBM3ExMUNRM1FBIVNRYPFg8UEhQ1FhAVDxE5ExITNxM2EjcTExM2EwAFPwABJEkTAA0FAAAAAAAAAAA=' 
    right_tv_q:
      friendly_name: 'Direita TV Quarto'
      command_on: 'JgBQAAABKI0VEBYQFBAXERESExMSExQREzYXMxcyEzgWNBY0EhIUNhITEzcTEhcOFg8VERU0FBEUNhYPFzIXMxM2FDYTEhU0FgAFPAABJkYYAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKI0VEBYQFBAXERESExMSExQREzYXMxcyEzgWNBY0EhIUNhITEzcTEhcOFg8VERU0FBEUNhYPFzIXMxM2FDYTEhU0FgAFPAABJkYYAA0FAAAAAAAAAAA=' 
    left_tv_q:
      friendly_name: 'Esquerda TV Quarto'
      command_on: 'JgBUAAABJ44WDxYQFRAVEBYPExMTEhMTFTQWMxY0FjMWMxY0Fg8TNhQSEhMTExITExISExczFg8WMxczEzYTNhQ2FTQWEBYyFwAFOwABKEYVAAQlCwANBQAAAAA='
      command_off: 'JgBUAAABJ44WDxYQFRAVEBYPExMTEhMTFTQWMxY0FjMWMxY0Fg8TNhQSEhMTExITExISExczFg8WMxczEzYTNhQ2FTQWEBYyFwAFOwABKEYVAAQlCwANBQAAAAA=' 
    ok_tv_q:
      friendly_name: 'OK TV Quarto'
      command_on: 'JgBYAAABJ48TEhMSExMSExMSExITExITEzYXMxQ1FTYWMxYzFhASNxYzFw8UERUREhMVEBE4ExMUERM1FDcSNxM2FzMSExY0FgAFOwABJ0cWAAxIAAEoRBUADQU='
      command_off: 'JgBYAAABJ48TEhMSExMSExMSExITExITEzYXMxQ1FTYWMxYzFhASNxYzFw8UERUREhMVEBE4ExMUERM1FDcSNxM2FzMSExY0FgAFOwABJ0cWAAxIAAEoRBUADQU='
    um_net_q:
      friendly_name: '1 Net Quarto'
      command_on: 'JgBUAAoABOUAASiPEzcTNhQ1Fw0XDhUQFg8SNhQRFTQXMhY0EzYUEBczFg4WMxYPFw4SExMRExEVEBYOFg8VNBYzEzYUNhM2FjMWMxQABO4AASZJFwANBQAAAAA='
      command_off: 'JgBUAAoABOUAASiPEzcTNhQ1Fw0XDhUQFg8SNhQRFTQXMhY0EzYUEBczFg4WMxYPFw4SExMRExEVEBYOFg8VNBYzEzYUNhM2FjMWMxQABO4AASZJFwANBQAAAAA='
    dois_net_q:
      friendly_name: '2 Net Quarto'
      command_on: 'JgBQAAABKo8WMxM2EzcTERMSExETEhcyFg8UNRcyFzIWMxQRFTQVEBUPFjQWDhYPFg4WDxETFBISNhYPFjMTNhQ1EzcWMxYzFgAE7AABJkkTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKo8WMxM2EzcTERMSExETEhcyFg8UNRcyFzIWMxQRFTQVEBUPFjQWDhYPFg4WDxETFBISNhYPFjMTNhQ1EzcWMxYzFgAE7AABJkkTAA0FAAAAAAAAAAA='
    tres_net_q:
      friendly_name: '3 Net Quarto'
      command_on: 'JgBUAAABKY0ZMhYzFjMUERYPFQ8WDxU0Fw0TNxQ1EzYXMhQRFzIUERM2FTQWDxYOFBERExEWERETEhMRFjQWMxcyEzYUNRgyFwAE6wABJkkTAAScCgANBQAAAAA='
      command_off: 'JgBUAAABKY0ZMhYzFjMUERYPFQ8WDxU0Fw0TNxQ1EzYXMhQRFzIUERM2FTQWDxYOFBERExEWERETEhMRFjQWMxcyEzYUNRgyFwAE6wABJkkTAAScCgANBQAAAAA='
    quatro_net_q:
      friendly_name: '4 Net Quarto'
      command_on: 'JgBUAAsAB0IAASqOFzITNhM2FBEVEBYQExAUNRQQFzMTNhM2FzIWDxYzFg8VDxYPEzYTERcOFg8VDxcPEjYUNRcOFjUTNhM2EzYXMxcABOsAASVKEwANBQAAAAA='
      command_off: 'JgBUAAsAB0IAASqOFzITNhM2FBEVEBYQExAUNRQQFzMTNhM2FzIWDxYzFg8VDxYPEzYTERcOFg8VDxcPEjYUNRcOFjUTNhM2EzYXMxcABOsAASVKEwANBQAAAAA='
    cinco_net_q:
      friendly_name: '5 Net Quarto'
      command_on: 'JgBQAAABKY8YMRM2EzYTEhMSEhIWDxU0Fg8VNBYzFTQTNhQRFzITERQ2Fw0WMxYPExIUEBUQFw0WEBA4ExIUNRcyFjMWMxM3EwAE7gABKUcXAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKY8YMRM2EzYTEhMSEhIWDxU0Fg8VNBYzFTQTNhQRFzITERQ2Fw0WMxYPExIUEBUQFw0WEBA4ExIUNRcyFjMWMxM3EwAE7gABKUcXAA0FAAAAAAAAAAA='
    seis_net_q:
      friendly_name: '6 Net Quarto'
      command_on: 'JgBQAAABKY4XMhQ2FTQWDhYPFBMTExM0FBEROBM2EzYXMxcNFjMUERQRFTQWMxYQFA8VEBMSEhIUNRcQFA4UNRM3EzYTNRgyFgAE7QABKEYWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKY4XMhQ2FTQWDhYPFBMTExM0FBEROBM2EzYXMxcNFjMUERQRFTQWMxYQFA8VEBMSEhIUNRcQFA4UNRM3EzYTNRgyFgAE7QABKEYWAA0FAAAAAAAAAAA='
    sete_net_q:
      friendly_name: '7 Net Quarto'
      command_on: 'JgBQAAABKY4YMhQ1FTQWDxYOFg8VDxczExETNhM3FjMWMxYPFjMXDRM3EzYTNhMSExEXEBQPFQ8UEBUQFg8UNRcyFjMWMxY0FgAE6gABJ0oTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKY4YMhQ1FTQWDxYOFg8VDxczExETNhM3FjMWMxYPFjMXDRM3EzYTNhMSExEXEBQPFQ8UEBUQFg8UNRcyFjMWMxY0FgAE6gABJ0oTAA0FAAAAAAAAAAA='
    oito_net_q:
      friendly_name: '8 Net Quarto'
      command_on: 'JgBQAAABKI8WNBM2EzYWDxQQExIWDhYwFxEVNBYzFzMXMhMRFjQWDhYPFQ8XERYyFg8WDhMSExEVNRcxFjQWDxE4EzYTNhYzFgAE7QABKUYWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKI8WNBM2EzYWDxQQExIWDhYwFxEVNBYzFzMXMhMRFjQWDhYPFQ8XERYyFg8WDhMSExEVNRcxFjQWDxE4EzYTNhYzFgAE7QABKUYWAA0FAAAAAAAAAAA='
    nove_net_q:
      friendly_name: '9 Net Quarto'
      command_on: 'JgBQAAABJZIUNRYzFjQWDhYPFg4TEhYzFg8WMxYzFjMWNBMRFTQTEhM2ExIVDxYzFg8WDxYOFBEXDRYzFjQUEBU0FjQWMxcyFAAE7wABJUkTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJZIUNRYzFjQWDhYPFg4TEhYzFg8WMxYzFjMWNBMRFTQTEhM2ExIVDxYzFg8WDxYOFBEXDRYzFjQUEBU0FjQWMxcyFAAE7wABJUkTAA0FAAAAAAAAAAA='
    zero_net_q:
      friendly_name: '0 Net Quarto'
      command_on: 'JgBQAAABKI8UNhM2FTcVDxYOERQWDhU1ERMROBQ2EzUYMRcOFjQTERMSExEVEBYRFA4WFxQQFxAUMxYzFzITNxM2FDUVNBYzFwAE7AABJ0gUAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKI8UNhM2FTcVDxYOERQWDhU1ERMROBQ2EzUYMRcOFjQTERMSExEVEBYRFA4WFxQQFxAUMxYzFzITNxM2FDUVNBYzFwAE7AABJ0gUAA0FAAAAAAAAAAA='
    mute_tv_q:
      friendly_name: 'Mute TV Quarto'
      command_on: 'JgBUAAsAAysAASmOGA0UERYOFw4XDRYQEhEWDxcyFjMUNhcyFjMWMxQRFzIWMxYPFzITEhM2Fg4XDhcNFhASNhYPFzIXDhU0FDUUNRcABTUAASlGFgANBQAAAAA='
      command_off: 'JgBUAAsAAysAASmOGA0UERYOFw4XDRYQEhEWDxcyFjMUNhcyFjMWMxQRFzIWMxYPFzITEhM2Fg4XDhcNFhASNhYPFzIXDhU0FDUUNRcABTUAASlGFgANBQAAAAA='
- platform: broadlink
  host: 192.168.86.37
  mac: '34:ea:34:b5:32:c5'
  friendly_name: 'Sala'
  switches:
    power_net_s:
      friendly_name: 'Power Net Sala'
      command_on: 'JgBYAAABJpIUNxI3EzYTEhMRExMSExI2ExITNxI4ETcUNhMSEzcSExIREzcTExISEjcTERMTEhMSNhMSEzYTOBISEzYTNxM2EwAFBwABKUgTAAxcAAEnSBMADQU='
      command_off: 'JgBYAAABJpIUNxI3EzYTEhMRExMSExI2ExITNxI4ETcUNhMSEzcSExIREzcTExISEjcTERMTEhMSNhMSEzYTOBISEzYTNxM2EwAFBwABKUgTAAxcAAEnSBMADQU='
    power_tv_s:
      friendly_name: 'Power TV Sala'
      command_on: 'JgCMAJSSFTYRNxQ2FBETERQSExISExI2EzcUNRUQFBETEhMTEhITEhI3FBAUERQRExMTEhMREzcTEhI2FDYUNRQ2EzYUNhMABgGUkhQ1FDYTNxQRExMSExIRFBEUNhQ1FDYUERMSExISExISExEUNhQRExITEhMSEhITExI3ExISNxQ2ETgTNhM3EzcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJSSFTYRNxQ2FBETERQSExISExI2EzcUNRUQFBETEhMTEhITEhI3FBAUERQRExMTEhMREzcTEhI2FDYUNRQ2EzYUNhMABgGUkhQ1FDYTNxQRExMSExIRFBEUNhQ1FDYUERMSExISExISExEUNhQRExITEhMSEhITExI3ExISNxQ2ETgTNhM3EzcTAA0FAAAAAAAAAAAAAAAA'
    source_tv_s:
      friendly_name: 'Source TV Sala'
      command_on: 'JgCMAJKSFDYTNxI4ERITERQRFBEUEBQ2EzYTNxIRExEUERMTEhETNhMRExIUERISEhMSEhIRExEUNhQ1FTUUNRU1EzYUNxIABgyTkhQ1FDYTNxMSEhEUEBQQFBETNhQ2FDYUERQQExEUERESEzYUERMSEhITEhMQFBAVEBMRFDYUORM3EzUTNxQ1EzcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJKSFDYTNxI4ERITERQRFBEUEBQ2EzYTNxIRExEUERMTEhETNhMRExIUERISEhMSEhIRExEUNhQ1FTUUNRU1EzYUNxIABgyTkhQ1FDYTNxMSEhEUEBQQFBETNhQ2FDYUERQQExEUERESEzYUERMSEhITEhMQFBAVEBMRFDYUORM3EzUTNxQ1EzcTAA0FAAAAAAAAAAAAAAAA'
    vol_up_tv_s:
      friendly_name: 'Vol Cima TV Sala'
      command_on: 'JgBGAJSSFDUUNRQ2FBITERMSExITERM3EzUUNRQSExITERMSExITNhM2EzcTEhMQFBITEhMRExITEhMREzYUNhM2EzcTNhMADQUAAA=='
      command_off: 'JgBGAJSSFDUUNRQ2FBITERMSExITERM3EzUUNRQSExITERMSExITNhM2EzcTEhMQFBITEhMRExITEhMREzYUNhM2EzcTNhMADQUAAA=='
    vol_down_tv_s:
      friendly_name: 'Vol Baixo TV Sala'
      command_on: 'JgCMAJKRFDYUNRM3ExITERIRFBETERM3E0ESNhUREhETEhQQExITNxI3ExEUNiIRExMSERQQExMTERI3ExISNhQ2EzcTNxIABgyTkhQ1FDYUNhMRExISExIRFBETNhQ1FDUUEBUQFBAVDxUREzUVNhMQFDYUEBQQFRAUEBMSExITNhISFDYTNhQ2EjcUAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJKRFDYUNRM3ExITERIRFBETERM3E0ESNhUREhETEhQQExITNxI3ExEUNiIRExMSERQQExMTERI3ExISNhQ2EzcTNxIABgyTkhQ1FDYUNhMRExISExIRFBETNhQ1FDUUEBUQFBAVDxUREzUVNhMQFDYUEBQQFRAUEBMSExITNhISFDYTNhQ2EjcUAA0FAAAAAAAAAAAAAAAA'
    ch_up_net_s:
      friendly_name: 'Canal Cima Net Sala'
      command_on: 'JgBYAAABJpIUNhM3FDYTExISEhITExI3EhMSNhM3EzcTNxISEzYTExISExISExIREzcTEhMSEhITNhM4EjcTNxIRFDYTNxM3EgAFCQABJ0kSAAxcAAEnSRIADQU='
      command_off: 'JgBYAAABJpIUNhM3FDYTExISEhITExI3EhMSNhM3EzcTNxISEzYTExISExISExIREzcTEhMSEhITNhM4EjcTNxIRFDYTNxM3EgAFCQABJ0kSAAxcAAEnSRIADQU='
    ch_down_net_s:
      friendly_name: 'Canal Baixo Net Sala'
      command_on: 'JgBYAAABKJMSNhM3EzYUEhITEhETEhM3ExEUNhQ1FDYTNxMSEjYUERMTEjcSEhM2FDYTExISEhITNhQREzgSEhIfEjYUNhQ1FAAFCAABJ0gUAAxaAAEoSBMADQU='
      command_off: 'JgBYAAABKJMSNhM3EzYUEhITEhETEhM3ExEUNhQ1FDYTNxMSEjYUERMTEjcSEhM2FDYTExISEhITNhQREzgSEhIfEjYUNhQ1FAAFCAABJ0gUAAxaAAEoSBMADQU='
    up_tv_s:
      friendly_name: 'Cima TV Sala'
      command_on: 'JgCMAJKTEjcTNhQ2ExIUEBMSEhMSERM2EzYUNhQSERITEhMREhEUERMSExETEhISEzUUNhUPEzcUNRM3FDYTNxISEhITNhQABguTkhQ1FTUTNhYQEhISEhMSEhMRNhQ2EzgTERMSERITERMSEhMSEhISEhMSEhM1FTUTEhM3EjcSNxQ1FDYTEhISEzcSAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJKTEjcTNhQ2ExIUEBMSEhMSERM2EzYUNhQSERITEhMREhEUERMSExETEhISEzUUNhUPEzcUNRM3FDYTNxISEhITNhQABguTkhQ1FTUTNhYQEhISEhMSEhMRNhQ2EzgTERMSERITERMSEhMSEhISEhMSEhM1FTUTEhM3EjcSNxQ1FDYTEhISEzcSAA0FAAAAAAAAAAAAAAAA'
    down_tv_s:
      friendly_name: 'Baixo TV Sala'
      command_on: 'JgCMAJOSFDUVNRU1FBETEhIRFBETERM2FDYTNhQRExETERMSFBATNhQSExETERMSEjcUNhMRExMRNxM2FDYTNRUREhEUNhQABgqVkRU0EzcUNhMRExITERIRFBEUNRQ1FTUTEhMSExEUEBMSEjcTEhIRFBAUERM2FDYTEhMREzcTNhM3EzcSERQREzYTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJOSFDUVNRU1FBETEhIRFBETERM2FDYTNhQRExETERMSFBATNhQSExETERMSEjcUNhMRExMRNxM2FDYTNRUREhEUNhQABgqVkRU0EzcUNhMRExITERIRFBEUNRQ1FTUTEhMSExEUEBMSEjcTEhIRFBAUERM2FDYTEhMREzcTNhM3EzcSERQREzYTAA0FAAAAAAAAAAAAAAAA'
    right_tv_s:
      friendly_name: 'Direita TV Sala'
      command_on: 'JgDSAJORFDUVNRQ1FBITERISFBESEhM2EzcTNxMRExESExISEhETEhQ1FBETEhIREzgSNxISFDYSERM3EzcSOA8UFBAUNhMABgyUkhI3EjcTNhQRExMSERITEhISNhU2EjcTEhMREhEVEBMRFBETNxISExEUERI2FDYTERM4EhETNxM3EjcUERIREzcTAAYMkZMUNhQ1FTYTEhMSExESEhMREzYUNxI2FBETEhISEhMTERIRFjQTERMSExETNxM2FBISNhQSETYUNhQ1FBETEhM2EwANBQAAAAAAAA=='
      command_off: 'JgDSAJORFDUVNRQ1FBITERISFBESEhM2EzcTNxMRExESExISEhETEhQ1FBETEhIREzgSNxISFDYSERM3EzcSOA8UFBAUNhMABgyUkhI3EjcTNhQRExMSERITEhISNhU2EjcTEhMREhEVEBMRFBETNxISExEUERI2FDYTERM4EhETNxM3EjcUERIREzcTAAYMkZMUNhQ1FTYTEhMSExESEhMREzYUNxI2FBETEhISEhMTERIRFjQTERMSExETNxM2FBISNhQSETYUNhQ1FBETEhM2EwANBQAAAAAAAA=='
    left_tv_s:
      friendly_name: 'Esquerda TV Sala'
      command_on: 'JgCMAJOSEzYSNxU2EhEUERQSERETExI3EjcUNRMRFBITEhIRExISNhMSEzYUERMTETYTNxQQFBETNBUSEjgSNxIRGxMSNxMABguTkhM3FDYUNRQSERITEhISEhITNxM2FDcRERMTEhISExESEzYTExA4ExISExI3EjcTEhISEjcTEhI2FDYUEBMTEjcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJOSEzYSNxU2EhEUERQSERETExI3EjcUNRMRFBITEhIRExISNhMSEzYUERMTETYTNxQQFBETNBUSEjgSNxIRGxMSNxMABguTkhM3FDYUNRQSERITEhISEhITNxM2FDcRERMTEhISExESEzYTExA4ExISExI3EjcTEhISEjcTEhI2FDYUEBMTEjcTAA0FAAAAAAAAAAAAAAAA'
    ok_tv_s:
      friendly_name: 'OK TV Sala'
      command_on: 'JgCMAJOSEzUVNRQ1FRAUEBMSExISEhI3FDUUNxMREhEUERQQFBEUDxUREhIYNhQQFEAUNhMREzcTNhQ2ExESNxQQExEVNRQABgqVkhM2EzcTNhMRExISERMRFBETNxM2FDUVEBMSEhISExIRExIUEBQQE0AVERM2EzcTERM3EzYTNxMREjYVEBQQFDYUAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJOSEzUVNRQ1FRAUEBMSExISEhI3FDUUNxMREhEUERQQFBEUDxUREhIYNhQQFEAUNhMREzcTNhQ2ExESNxQQExEVNRQABgqVkhM2EzcTNhMRExISERMRFBETNxM2FDUVEBMSEhISExIRExIUEBQQE0AVERM2EzcTERM3EzYTNxMREjYVEBQQFDYUAA0FAAAAAAAAAAAAAAAA'
    um_net_s:
      friendly_name: '1 Net Sala'
      command_on: 'JgBYAAABJ5IUORI3EjcTERQRExMSEhM2ExITNxI3FDUTNxMSEjgSEhM2ExITEhMSEhITEhISExETExI3EzcTNxI2EzcTNxQ2EgAFCAABKEkTAAxaAAEnShMADQU='
      command_off: 'JgBYAAABJ5IUORI3EjcTERQRExMSEhM2ExITNxI3FDUTNxMSEjgSEhM2ExITEhMSEhITEhISExETExI3EzcTNxI2EzcTNxQ2EgAFCAABKEkTAAxaAAEnShMADQU='      
    dois_net_s:
      friendly_name: '2 Net Sala'
      command_on: 'JgBYAAABJpIUNhQ1FDYUEBMTEhITEhA5ExEUNhM3EzcSNxMREzgSEhMSEjcTEhITEhITEhISExETOBESFDYTNhQ2EzgSNxI3EwAFCAABJ0kUAAxaAAEnSBQADQU='
      command_off: 'JgBYAAABJpIUNhQ1FDYUEBMTEhITEhA5ExEUNhM3EzcSNxMREzgSEhMSEjcTEhITEhITEhISExETOBESFDYTNhQ2EzgSNxI3EwAFCAABJ0kUAAxaAAEnSBQADQU='
    tres_net_s:
      friendly_name: '3 Net Sala'
      command_on: 'JgBYAAABJpMTNxM2EzcSEhMSEhMSEhM2ExEUNhM4EjcSOBIRFDYTExI3EjgSEhISFRMSEhITEhITEhISEzYTNxM2EzgSNxM2EwAFCAABKEgUAAxaAAEnSRQADQU='
      command_off: 'JgBYAAABJpMTNxM2EzcSEhMSEhMSEhM2ExEUNhM4EjcSOBIRFDYTExI3EjgSEhISFRMSEhITEhITEhISEzYTNxM2EzgSNxM2EwAFCAABKEgUAAxaAAEnSRQADQU='      
    quatro_net_s:
      friendly_name: '4 Net Sala'
      command_on: 'JgBYAAABKJIUNRQ2EzcTEhITEhEUERM4EhISNxM2EzcTNxMSEjgTEBMSExITNhMTEhETEhMSExISOBI2ExITNxM3EjgSNhQ2FAAFBwABJ0kTAAxaAAEoSBMADQU='
      command_off: 'JgBYAAABKJIUNRQ2EzcTEhITEhEUERM4EhISNxM2EzcTNxMSEjgTEBMSExITNhMTEhETEhMSExISOBI2ExITNxM3EjgSNhQ2FAAFBwABJ0kTAAxaAAEoSBMADQU='      
    cinco_net_s:
      friendly_name: '5 Net Sala'
      command_on: 'JgBYAAABJpEUNxI4EjYUERMRFBISExI3EhMSNxM3EjcTNhMTEjcSEhM2FBETOBISExISEhMRExMSEhM3EhITNhU4EzYSNxM2FAAFCAABJ0gUAAxaAAEoSBMADQU='
      command_off: 'JgBYAAABJpEUNxI4EjYUERMRFBISExI3EhMSNxM3EjcTNhMTEjcSEhM2FBETOBISExISEhMRExMSEhM3EhITNhU4EzYSNxM2FAAFCAABJ0gUAAxaAAEoSBMADQU='
    seis_net_s:
      friendly_name: '6 Net Sala'
      command_on: 'JgBYAAABKJIUNRM4EzYTEhISExISExI2FBETNxM2EzcTNxUSEjcTFBISEzcTNxISExETEhMSExISNxMSEhITNhQ2EzcUNhI3EwAFCAABJ0kTAAxaAAEoRxQADQU='
      command_off: 'JgBYAAABKJIUNRM4EzYTEhISExISExI2FBETNxM2EzcTNxUSEjcTFBISEzcTNxISExETEhMSExISNxMSEhITNhQ2EzcUNhI3EwAFCAABJ0kTAAxaAAEoRxQADQU='  
    sete_net_s:
      friendly_name: '7 Net Sala'
      command_on: 'JgBYAAABJ5IUNhM3EjgPFBMSExMSEhI4EhEUNhM3EzcSOBIREzcTEhM3EjgSNhMSExISExISExETExISExISNxM2EzgTNhI4DwAFCwABKEkSAAxbAAEoSRIADQU='
      command_off: 'JgBYAAABJ5IUNhM3EjgPFBMSExMSEhI4EhEUNhM3EzcSOBIREzcTEhM3EjgSNhMSExISExISExETExISExISNxM2EzgTNhI4DwAFCwABKEkSAAxbAAEoSRIADQU='  
    oito_net_s:
      friendly_name: '8 Net Sala'
      command_on: 'JgBYAAABKJIUNhI3EzYTExISExISEhM2ExMSNxM3EjYUNhMTEjcSExIRFBETEhM3EhMSERQRExITNxM3EjcTEhI3EzYTOBI3EgAFCAABKEkTAAxbAAEqSBIADQU='
      command_off: 'JgBYAAABKJIUNhI3EzYTExISExISEhM2ExMSNxM3EjYUNhMTEjcSExIRFBETEhM3EhMSERQRExITNxM3EjcTEhI3EzYTOBI3EgAFCAABKEkTAAxbAAEqSBIADQU='
    nove_net_s:
      friendly_name: '9 Net Sala'
      command_on: 'JgBYAAABKJMSNhQ5EjgSERMSExITEhI4EhETNxM3EjgSNhQREzcUEBM3ExITEhI4EhETEhMSExISEw85EzcTEhM3EjgSNxI3FAAFCAABJkkTAAxcAAEmSRMADQU='
      command_off: 'JgBYAAABKJMSNhQ5EjgSERMSExITEhI4EhETNxM3EjgSNhQREzcUEBM3ExITEhI4EhETEhMSExISEw85EzcTEhM3EjgSNxI3FAAFCAABJkkTAAxcAAEmSRMADQU='
    zero_net_s:
      friendly_name: '0 Net Sala'
      command_on: 'JgBYAAABJpMTNhM3EjcUEBMSExMSEhI3ExETOBM2EzcSNxMSEjcTEhMSEhITEhISExEUEhITEhIPOhM2FDYUNhM3EzcSNxI3EwAFCAABJ0kUAAxZAAEoSBMADQU='
      command_off: 'JgBYAAABJpMTNhM3EjcUEBMSExMSEhI3ExETOBM2EzcSNxMSEjcTEhMSEhITEhISExEUEhITEhIPOhM2FDYUNhM3EzcSNxI3EwAFCAABJ0kUAAxZAAEoSBMADQU='
    mute_tv_s:
      friendly_name: 'Mute TV Sala'
      command_on: 'JgCMAJORFTUUNhM2ExITERIRFBETEhM2FDUUNhUQEhISERUQFBAUNRU1EzcTNxMRExITERMRFBESEhISFBETNhM3EjYVNhMABguTkxU1FDUVNRQRFBAUERMRFBETNRM4EzYTERQRExEPFBUQEzYVNRM2FDYUERISFBETERMRExITERMQFTYTNhQ2EzYUAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJORFTUUNhM2ExITERIRFBETEhM2FDUUNhUQEhISERUQFBAUNRU1EzcTNxMRExITERMRFBESEhISFBETNhM3EjYVNhMABguTkxU1FDUVNRQRFBAUERMRFBETNRM4EzYTERQRExEPFBUQEzYVNRM2FDYUERISFBETERMRExITERMQFTYTNhQ2EzYUAA0FAAAAAAAAAAAAAAAA'