- platform: tplink
  host: 192.168.86.27
  friendly_name: 'display'
  username: robsonschmidt@gmail.com
  password: 14253678
- platform: tplink
  host: 192.168.86.41
  friendly_name: 'garden_light'
  username: robsonschmidt@gmail.com
  password: 14253678
- platform: broadlink
  host: 192.168.86.43
  mac: '34:EA:34:B3:00:CB'
  friendly_name: 'Suite'
  type: rm_mini
  timeout: 60
  switches:
    power_net_q:
      friendly_name: 'Power Net Quarto'
      command_on: 'JgBQAAABJZIXMhY0FzIWDhUQExEUERYzFg8WMxYzFjMVNRMREzYTEhMSFTQWDhYRFDMWDxYOFRAROBMSEzYTNhMSEzYTNhU0FgAE7QABKEYWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJZIXMhY0FzIWDhUQExEUERYzFg8WMxYzFjMVNRMREzYTEhMSFTQWDhYRFDMWDxYOFRAROBMSEzYTNhMSEzYTNhU0FgAE7QABKEYWAA0FAAAAAAAAAAA='
    power_tv_q:
      friendly_name: 'Power TV Quarto'
      command_on: 'JgBUAA0AAakAASaSFw0WDxYOFRAUERMRExIVDxYzFzMWMxM2EzYUNRYPFjMXMhY0FBATEhcOFQ8WEBIRExITERM2EzcXMhYzFzIUNRMABTkAASVKEwANBQAAAAA='
      command_off: 'JgBUAA0AAakAASaSFw0WDxYOFRAUERMRExIVDxYzFzMWMxM2EzYUNRYPFjMXMhY0FBATEhcOFQ8WEBIRExITERM2EzcXMhYzFzIUNRMABTkAASVKEwANBQAAAAA='
    source_tv_q:
      friendly_name: 'Source TV Quarto'
      command_on: 'JgBQAAABJ44WDxYQFRAVEBUQFRMTEg8VEzYSNxM3EzYTMxo1ExITNhMTEjcTNhQ2EjcTExISFw8SNxYQFhETEBUQFTUWMxM2EwAFPwABJkgVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ44WDxYQFRAVEBUQFRMTEg8VEzYSNxM3EzYTMxo1ExITNhMTEjcTNhQ2EjcTExISFw8SNxYQFhETEBUQFTUWMxM2EwAFPwABJkgVAA0FAAAAAAAAAAA='
    vol_up_tv_q:
      friendly_name: 'Vol Cima TV Quarto'
      command_on: 'JgBQAAABJ44XDxYPEhMTEhMTEhMTExISFDYXMxYzFjMWNBU0Fw8UNBQSEzcSNxQREzYWEBYPFw4VNRQRFRIUMxQSEjcTNxM2EwAFPwABJEoTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ44XDxYPEhMTEhMTEhMTExISFDYXMxYzFjMWNBU0Fw8UNBQSEzcSNxQREzYWEBYPFw4VNRQRFRIUMxQSEjcTNxM2EwAFPwABJEoTAA0FAAAAAAAAAAA='
    vol_down_tv_q:
      friendly_name: 'Vol Baixo TV Quarto'
      command_on: 'JgBYAAABJJEVEBYSEBQUEhMQFRMQFRMREjYXMxU1EzYTNhM3ExIVNBcOFjQTExUzFDYTEhMTFRAVNBYQFDUWDxYPFTUTNxM1FAAFPgABJEoTAAxMAAEkShIADQU='
      command_off: 'JgBYAAABJJEVEBYSEBQUEhMQFRMQFRMREjYXMxU1EzYTNhM3ExIVNBcOFjQTExUzFDYTEhMTFRAVNBYQFDUWDxYPFTUTNxM1FAAFPgABJEoTAAxMAAEkShIADQU='
    ch_up_net_q:
      friendly_name: 'Canal Cima Net Quarto'
      command_on: 'JgBQAAABKJAWMxYzFjMWDxYOFg8WEBczFg8VMxQ2EzYUNRQREzYTEhUPFhAVEBQREzQWEBUOEhQSNhQ1EzYVNRYOFjMWNBYzFgAE7QABKEYWAA0FAAAAAAAAAAA='
      command_off: 'JgBWAAkABtsLgQABJ48TNxQ1FjMTEhMRFRAWDhY0FBAWMxY0FTQWMxYPFjMWDhYPEjcXDhYzFjMWDxYOFg8WMxYPFjMWDhMSEzYUNRM3FQAE7QABKUYWAA0FAAA='
    ch_down_net_q:
      friendly_name: 'Canal Baixo Net Quarto'
      command_on: 'JgBQAAABKJAWMxYzFjMWDxYOFg8WEBczFg8VMxQ2EzYUNRQREzYTEhUPFhAVEBQREzQWEBUOEhQSNhQ1EzYVNRYOFjMWNBYzFgAE7QABKEYWAA0FAAAAAAAAAAA='
      command_off: 'JgBWAAkABtsLgQABJ48TNxQ1FjMTEhMRFRAWDhY0FBAWMxY0FTQWMxYPFjMWDhYPEjcXDhYzFjMWDxYOFg8WMxYPFjMWDhMSEzYUNRM3FQAE7QABKUYWAA0FAAA='
    up_tv_q:
      friendly_name: 'Cima TV Quarto'
      command_on: 'JgBQAAABJ44VEBkMFhAZCxcPGQwWEBkMGDEWNBcyGTEZMBgxGQ0WMxkvFxAYMRYzGTEVEBkPFBAZDBU0GQ0YDRYPGTEVNBczGAAFOQABJ0cWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ48WDxUREhMVEBMSFw8VERQQFjMTNhM3FDYSNxQ1FBITNhQ1Fg8YNBYQFRAWDxI3FBISExM2FBETMhs0EjYXEBU0FAAFPQABJkcXAA0FAAAAAAAAAAA='
    down_tv_q:
      friendly_name: 'Baixo TV Quarto'
      command_on: 'JgBQAAABJ44VEBkMFhAZCxcPGQwWEBkMGDEWNBcyGTEZMBgxGQ0WMxkvFxAYMRYzGTEVEBkPFBAZDBU0GQ0YDRYPGTEVNBczGAAFOQABJ0cWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ48WDxUREhMVEBMSFw8VERQQFjMTNhM3FDYSNxQ1FBITNhQ1Fg8YNBYQFRAWDxI3FBISExM2FBETMhs0EjYXEBU0FAAFPQABJkcXAA0FAAAAAAAAAAA=' 
    right_tv_q:
      friendly_name: 'Direita TV Quarto'
      command_on: ''
      command_off: '' 
    left_tv_q:
      friendly_name: 'Esquerda TV Quarto'
      command_on: ''
      command_off: '' 
    ok_tv_q:
      friendly_name: 'OK TV Quarto'
      command_on: ''
      command_off: ''
    um_net_q:
      friendly_name: '1 Net Quarto'
      command_on: ''
      command_off: ''      
    dois_net_q:
      friendly_name: '2 Net Quarto'
      command_on: ''
      command_off: ''      
    tres_net_q:
      friendly_name: '3 Net Quarto'
      command_on: ''
      command_off: ''      
    quarto_net_q:
      friendly_name: '4 Net Quarto'
      command_on: ''
      command_off: ''      
    cinco_net_q:
      friendly_name: '5 Net Quarto'
      command_on: ''
      command_off: ''      
    seis_net_q:
      friendly_name: '6 Net Quarto'
      command_on: ''
      command_off: ''      
    sete_net_q:
      friendly_name: '7 Net Quarto'
      command_on: ''
      command_off: ''      
    oito_net_q:
      friendly_name: '8 Net Quarto'
      command_on: ''
      command_off: ''      
    nove_net_q:
      friendly_name: '9 Net Quarto'
      command_on: ''
      command_off: ''      
    zero_net_q:
      friendly_name: '0 Net Quarto'
      command_on: ''
      command_off: ''      
- platform: broadlink
  host: 192.168.86.37
  mac: '34:ea:34:b5:32:c5'
  friendly_name: 'Sala'
  switches:
    power_net_s:
      friendly_name: 'Power Net Sala'
      command_on: 'JgBYAAABJpIUNxI3EzYTEhMRExMSExI2ExITNxI4ETcUNhMSEzcSExIREzcTExISEjcTERMTEhMSNhMSEzYTOBISEzYTNxM2EwAFBwABKUgTAAxcAAEnSBMADQU='
      command_off: 'JgBYAAABJpIUNxI3EzYTEhMRExMSExI2ExITNxI4ETcUNhMSEzcSExIREzcTExISEjcTERMTEhMSNhMSEzYTOBISEzYTNxM2EwAFBwABKUgTAAxcAAEnSBMADQU='
    power_tv_s:
      friendly_name: 'Power TV Sala'
      command_on: 'JgCMAJSSFTYRNxQ2FBETERQSExISExI2EzcUNRUQFBETEhMTEhITEhI3FBAUERQRExMTEhMREzcTEhI2FDYUNRQ2EzYUNhMABgGUkhQ1FDYTNxQRExMSExIRFBEUNhQ1FDYUERMSExISExISExEUNhQRExITEhMSEhITExI3ExISNxQ2ETgTNhM3EzcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJSSFTYRNxQ2FBETERQSExISExI2EzcUNRUQFBETEhMTEhITEhI3FBAUERQRExMTEhMREzcTEhI2FDYUNRQ2EzYUNhMABgGUkhQ1FDYTNxQRExMSExIRFBEUNhQ1FDYUERMSExISExISExEUNhQRExITEhMSEhITExI3ExISNxQ2ETgTNhM3EzcTAA0FAAAAAAAAAAAAAAAA'
    source_tv_s:
      friendly_name: 'Source TV Sala'
      command_on: 'JgCMAJKSFDYTNxI4ERITERQRFBEUEBQ2EzYTNxIRExEUERMTEhETNhMRExIUERISEhMSEhIRExEUNhQ1FTUUNRU1EzYUNxIABgyTkhQ1FDYTNxMSEhEUEBQQFBETNhQ2FDYUERQQExEUERESEzYUERMSEhITEhMQFBAVEBMRFDYUORM3EzUTNxQ1EzcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJKSFDYTNxI4ERITERQRFBEUEBQ2EzYTNxIRExEUERMTEhETNhMRExIUERISEhMSEhIRExEUNhQ1FTUUNRU1EzYUNxIABgyTkhQ1FDYTNxMSEhEUEBQQFBETNhQ2FDYUERQQExEUERESEzYUERMSEhITEhMQFBAVEBMRFDYUORM3EzUTNxQ1EzcTAA0FAAAAAAAAAAAAAAAA'
    vol_up_tv_s:
      friendly_name: 'Vol Cima TV Sala'
      command_on: ''
      command_off: ''
    vol_down_tv_s:
      friendly_name: 'Vol Baixo TV Sala'
      command_on: ''
      command_off: ''
    ch_up_net_s:
      friendly_name: 'Canal Cima Net Sala'
      command_on: ''
      command_off: ''
    ch_down_net_s:
      friendly_name: 'Canal Baixo Net Sala'
      command_on: ''
      command_off: ''
    up_tv_s:
      friendly_name: 'Cima TV Sala'
      command_on: ''
      command_off: ''
    down_tv_s:
      friendly_name: 'Baixo TV Sala'
      command_on: ''
      command_off: '' 
    right_tv_s:
      friendly_name: 'Direita TV Sala'
      command_on: ''
      command_off: '' 
    left_tv_s:
      friendly_name: 'Esquerda TV Sala'
      command_on: ''
      command_off: '' 
    ok_tv_s:
      friendly_name: 'OK TV Sala'
      command_on: ''
      command_off: ''
    um_net_s:
      friendly_name: '1 Net Sala'
      command_on: ''
      command_off: ''      
    dois_net_s:
      friendly_name: '2 Net Sala'
      command_on: ''
      command_off: ''      
    tres_net_s:
      friendly_name: '3 Net Sala'
      command_on: ''
      command_off: ''      
    quarto_net_s:
      friendly_name: '4 Net Sala'
      command_on: ''
      command_off: ''      
    cinco_net_s:
      friendly_name: '5 Net Sala'
      command_on: ''
      command_off: ''      
    seis_net_s:
      friendly_name: '6 Net Sala'
      command_on: ''
      command_off: ''      
    sete_net_s:
      friendly_name: '7 Net Sala'
      command_on: ''
      command_off: ''      
    oito_net_s:
      friendly_name: '8 Net Sala'
      command_on: ''
      command_off: ''      
    nove_net_s:
      friendly_name: '9 Net Sala'
      command_on: ''
      command_off: ''      
    zero_net_s:
      friendly_name: '0 Net Sala'
      command_on: ''
      command_off: ''