- platform: tplink
  host: 192.168.86.27
  friendly_name: 'display'
  username: robsonschmidt@gmail.com
  password: 14253678
- platform: tplink
  host: 192.168.86.41
  friendly_name: 'garden_light'
  username: robsonschmidt@gmail.com
  password: 14253678
- platform: broadlink
  host: 192.168.86.43
  mac: '34:EA:34:B3:00:CB'
  friendly_name: 'Suite'
  type: rm_mini
  timeout: 60
  switches:
    liga_net_q:
      friendly_name: 'Power Net Quarto'
      command_on: 'JgBQAAABJ5AXMxYzFjMWDxYOFg8TEhU0ExETNhM3EzYVNBYPFjMWDxUPFjMWDxUPFTUWDhYPEhQQOBQQFTQWNBYQFDMWNBYzFgAE7QABKEYVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ5AXMxYzFjMWDxYOFg8TEhU0ExETNhM3EzYVNBYPFjMWDxUPFjMWDxUPFTUWDhYPEhQQOBQQFTQWNBYQFDMWNBYzFgAE7QABKEYVAA0FAAAAAAAAAAA='
    liga_tv_q:
      friendly_name: 'Power TV Quarto'
      command_on: 'JgBYAAsAA/sWAAjCAAEojxUQExIUEBQRExEUERQRExEUNRM2EzcVNBU0FjMWDxYzFjMWNBUPFBEUEBYPFg8VDxYPEhMUNBY0FjMWMxYzFTQTAAU6AAEmSBQADQU='
      command_off: 'JgBYAAsAA/sWAAjCAAEojxUQExIUEBQRExEUERQRExEUNRM2EzcVNBU0FjMWDxYzFjMWNBUPFBEUEBYPFg8VDxYPEhMUNBY0FjMWMxYzFTQTAAU6AAEmSBQADQU='
    source_tv_q:
      friendly_name: 'Source TV Quarto'
      command_on: 'JgBcAAABJ4sZEBUQFhAVDxYQFRAWEBUREjYZMRU0FjMXMhY0GQ0UNRYPFjQaMBYzGTEVEBYQFRIUMxYPFhAVEhQPFTQTNxQ2EgACYwcAAtUAASdHFQAMSAABKEUVAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgBUAAkAAl4AASiMFhAWDhURFw4YDhQRFg8XDhgxGDIWMxU1FzIWMxcOFTUVNRYPGA0VEBgPFBEYMBcPFBEZMRcyFDUUNBY1FhAXMhcABTsAASdGGAANBQAAAAA='
    vol_tv_q:
      friendly_name: 'Vol TV Quarto'
      command_on: 'JgBUAAABJpITERQRExEVEBYPFg8VERQQFDQWMxM2EzYUNRM3FQ8WMxYPFjMWMxYPFjMWDxURExIUNRMSFQ8WNhUQFTMWNBU0FgAFNgABKEcWAAINDwANBQAAAAA='
      command_off: 'JgBQAAABJZITEhQQExIVDxYPFg8WDhYRFDMWMxYzEzcUNRcyFg8WMxYOFjQWDhYzFjQWDhUREhETNhQREzYTEhUPFjQWMxYzFgAFNgABKEcWAA0FAAAAAAAAAAA='
    canal_net_q:
      friendly_name: 'Canal Net Quarto'
      command_on: 'JgBQAAABKJAWMxYzFjMWDxYOFg8WEBczFg8VMxQ2EzYUNRQREzYTEhUPFhAVEBQREzQWEBUOEhQSNhQ1EzYVNRYOFjMWNBYzFgAE7QABKEYWAA0FAAAAAAAAAAA='
      command_off: 'JgBWAAkABtsLgQABJ48TNxQ1FjMTEhMRFRAWDhY0FBAWMxY0FTQWMxYPFjMWDhYPEjcXDhYzFjMWDxYOFg8WMxYPFjMWDhMSEzYUNRM3FQAE7QABKUYWAA0FAAA='
    tv_cima_q:
      friendly_name: 'Cima TV Quarto'
      command_on: 'JgBQAAABJ44VEBkMFhAZCxcPGQwWEBkMGDEWNBcyGTEZMBgxGQ0WMxkvFxAYMRYzGTEVEBkPFBAZDBU0GQ0YDRYPGTEVNBczGAAFOQABJ0cWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ48WDxUREhMVEBMSFw8VERQQFjMTNhM3FDYSNxQ1FBITNhQ1Fg8YNBYQFRAWDxI3FBISExM2FBETMhs0EjYXEBU0FAAFPQABJkcXAA0FAAAAAAAAAAA='
- platform: broadlink
  host: 192.168.86.37
  mac: '34:ea:34:b5:32:c5'
  friendly_name: 'Sala'
  switches:
    liga_net_s:
      friendly_name: 'Power Net Sala'
      command_on: 'JgBYAAABJpIUNxI3EzYTEhMRExMSExI2ExITNxI4ETcUNhMSEzcSExIREzcTExISEjcTERMTEhMSNhMSEzYTOBISEzYTNxM2EwAFBwABKUgTAAxcAAEnSBMADQU='
      command_off: 'JgBYAAABJpIUNxI3EzYTEhMRExMSExI2ExITNxI4ETcUNhMSEzcSExIREzcTExISEjcTERMTEhMSNhMSEzYTOBISEzYTNxM2EwAFBwABKUgTAAxcAAEnSBMADQU='
    liga_tv_s:
      friendly_name: 'Power TV Sala'
      command_on: 'JgCMAJSSFTYRNxQ2FBETERQSExISExI2EzcUNRUQFBETEhMTEhITEhI3FBAUERQRExMTEhMREzcTEhI2FDYUNRQ2EzYUNhMABgGUkhQ1FDYTNxQRExMSExIRFBEUNhQ1FDYUERMSExISExISExEUNhQRExITEhMSEhITExI3ExISNxQ2ETgTNhM3EzcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJSSFTYRNxQ2FBETERQSExISExI2EzcUNRUQFBETEhMTEhITEhI3FBAUERQRExMTEhMREzcTEhI2FDYUNRQ2EzYUNhMABgGUkhQ1FDYTNxQRExMSExIRFBEUNhQ1FDYUERMSExISExISExEUNhQRExITEhMSEhITExI3ExISNxQ2ETgTNhM3EzcTAA0FAAAAAAAAAAAAAAAA'
    source_tv_s:
      friendly_name: 'Source TV Sala'
      command_on: 'JgCMAJKSFDYTNxI4ERITERQRFBEUEBQ2EzYTNxIRExEUERMTEhETNhMRExIUERISEhMSEhIRExEUNhQ1FTUUNRU1EzYUNxIABgyTkhQ1FDYTNxMSEhEUEBQQFBETNhQ2FDYUERQQExEUERESEzYUERMSEhITEhMQFBAVEBMRFDYUORM3EzUTNxQ1EzcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJKSFDYTNxI4ERITERQRFBEUEBQ2EzYTNxIRExEUERMTEhETNhMRExIUERISEhMSEhIRExEUNhQ1FTUUNRU1EzYUNxIABgyTkhQ1FDYTNxMSEhEUEBQQFBETNhQ2FDYUERQQExEUERESEzYUERMSEhITEhMQFBAVEBMRFDYUORM3EzUTNxQ1EzcTAA0FAAAAAAAAAAAAAAAA'